# API Keys
OPENAI_API_KEY = "your-openai-api-key-here"
# You will need to replace "your-openai-api-key-here" with your actual OpenAI API key
# Add any other API keys you might be using below:
# SERPAPI_API_KEY = "your-serpapi-key-here"

# API Base URL
BASE_URL = "http://localhost:8000"

# Database configuration - if needed
# DATABASE_URL = "your-database-url"
